### Requires REST Client for VS Code
### https://marketplace.visualstudio.com/items?itemName=humao.rest-client
###
### Edit your settings.json and add the configuration from rest-client-config.json for local tests

### Read Metadata using OData V2
GET {{protocol}}://{{host}}:{{port}}/v2/catalog/$metadata

### Read Pictures
# curl http://localhost:4004/media/Pictures | jq
GET {{protocol}}://{{host}}:{{port}}/v2/catalog/BusinessCard


### Create second Picture
# curl -X POST http://localhost:4004/media/Pictures -H "Accept: application/json" -H "Content-Type: application/json" --data '{ "ID": "da07ae51-d0d3-41e7-a737-2555a213e5a9" }'
POST {{protocol}}://{{host}}:{{port}}/v2/catalog/BusinessCard
Accept: application/json
Content-Type: application/json

{ "ID": "da07ae51-d0d3-41e7-a737-2555a213e5a1" ,"fileType":"image/jpeg"}


### Upload second Binary
PUT {{protocol}}://{{host}}:{{port}}/v2/catalog/BusinessCard(da07ae51-d0d3-41e7-a737-2555a213e5a1)/imageFile
Content-Type: image/jpeg

< ./scan.jpg


### Read second Binary
# curl "http://localhost:4004/media/Pictures(da07ae51-d0d3-41e7-a737-2555a213e5a9)/content"
GET {{protocol}}://{{host}}:{{port}}/v2/catalog/BusinessCard(da07ae51-d0d3-41e7-a737-2555a213e5a1)/imageFile



### Execute Action second  a
POST  {{protocol}}://{{host}}:{{port}}/v2/catalog/BusinessCard_extractBusinessCardInfo?ID=guid%27da07ae51-d0d3-41e7-a737-2555a213e5a1%27
Content-Type: application/json

### Read second 
# curl "http://localhost:4004/media/Pictures(da07ae51-d0d3-41e7-a737-2555a213e5a9)/content"
GET {{protocol}}://{{host}}:{{port}}/v2/catalog/BusinessCard(da07ae51-d0d3-41e7-a737-2555a213e5a1)

### Delete second Image
# curl -X DELETE "http://localhost:4004/media/Pictures(da07ae51-d0d3-41e7-a737-2555a213e5a1)"
DELETE {{protocol}}://{{host}}:{{port}}/v2/catalog/BusinessCard(da07ae51-d0d3-41e7-a737-2555a213e5a1)
























### Create first Picture
# curl -X POST http://localhost:4004/media/Pictures -H "Accept: application/json" -H "Content-Type: application/json" --data '{ "ID": "da07ae51-d0d3-41e7-a737-2555a213e5a9" }'
POST {{protocol}}://{{host}}:{{port}}/v2/catalog/BusinessCard
Accept: application/json
Content-Type: application/json

{ "ID": "da07ae51-d0d3-41e7-a737-2555a213e5a9" ,"fileType":"image/jpeg"}




### Upload first Binary
PUT {{protocol}}://{{host}}:{{port}}/v2/catalog/BusinessCard(da07ae51-d0d3-41e7-a737-2555a213e5a9)/imageFile
Content-Type: image/jpeg

< ./Test.jpg

### Read first Binary
# curl "http://localhost:4004/media/Pictures(da07ae51-d0d3-41e7-a737-2555a213e5a9)/content"
GET {{protocol}}://{{host}}:{{port}}/v2/catalog/BusinessCard(da07ae51-d0d3-41e7-a737-2555a213e5a9)/imageFile

### Execute Action first a
POST  {{protocol}}://{{host}}:{{port}}/v2/catalog/BusinessCard_demo?ID=guid%27da07ae51-d0d3-41e7-a737-2555a213e5a9%27
Content-Type: application/json


### Read first 
# curl "http://localhost:4004/media/Pictures(da07ae51-d0d3-41e7-a737-2555a213e5a9)/content"
GET {{protocol}}://{{host}}:{{port}}/v2/catalog/BusinessCard(da07ae51-d0d3-41e7-a737-2555a213e5a9)

### Delete first Image
# curl -X DELETE "http://localhost:4004/media/Pictures(da07ae51-d0d3-41e7-a737-2555a213e5a9)"
DELETE {{protocol}}://{{host}}:{{port}}/v2/catalog/BusinessCard(da07ae51-d0d3-41e7-a737-2555a213e5a9)













### Execute Action
POST {{protocol}}://{{host}}:{{port}}/media/Pictures(da07ae51-d0d3-41e7-a737-2555a213e5a9)/extractBusinessCardInfo



### Create Picture in one request
# curl -v http://localhost:4004/media/Pictures -F file0=@./srv/tests/Test.png json='{ "ID": "da07ae51-d0d3-41e7-a737-2555a213e5a9" }' 
# This results in the following eror:
# {"error":{"code":null,"message":"No payload deserializer available for resource kind 'ENTITY' and mime type 'multipart/form-data'"}}* Rebuilt URL to: json= "ID": "da07ae51-d0d3-41e7-a737-2555a213e5a9"
